---
# tasks file for while_true_do.app_git

- name: Manage git Packages
  package:
    name: "{{ wtd_app_git_package }}"
    state: "{{ wtd_app_git_package_state }}"
  become: true
  tags:
    - git
    - package

- name: Include role Tasks
  include_tasks: "{{ wtd_app_git_role }}.yml"
  when: wtd_app_git_package_state != "absent"
