---
# tasks file for while_true_do.app_git

- name: Manage git Shell
  lineinfile:
    path: "/etc/shells"
    line: "{{ wtd_app_git_server_conf_shell }}"
  become: true
  tags:
    - git
    - configuration
    - service
    - shell

- name: Manage git Group
  group:
    name: "{{ wtd_app_git_server_conf_user.group }}"
    state: "present"
  become: true
  tags:
    - git
    - configuration
    - service
    - group

- name: Manage git User
  user:
    name: "{{ wtd_app_git_server_conf_user.name }}"
    home: "{{ wtd_app_git_server_conf_user.home }}"
    shell: "{{ wtd_app_git_server_conf_user.shell }}"
    groups: "{{ wtd_app_git_server_conf_user.group }}"
    state: "present"
    system: true
    password_lock: true
  become: true
  tags:
    - git
    - configuration
    - service
    - user

- name: Manage git User Authorized Keys
  authorized_key:
    user: "{{ wtd_app_git_server_conf_user.name }}"
    state: "{{ item.state | default('present') }}"
    key: "{{ item.key }}"
  loop: "{{ wtd_app_git_server_conf_authorized_key }}"
  become: true
  tags:
    - git
    - configuration
    - service
    - user

- name: Manage git Directory
  file:
    path: "{{ wtd_app_git_server_conf_dir }}"
    state: "directory"
    owner: "{{ wtd_app_git_server_conf_user.name }}"
    group: "{{ wtd_app_git_server_conf_user.group }}"
    mode: 0770
  become: true
  tags:
    - git
    - configuration
    - service
    - directory
