---
- name: Converge
  hosts: all
  roles:
    # Dependencies
    - role: while_true_do.rpo_epel
    # Client Installation
    - role: while_true_do.app_git
    # Server Installation
    - role: while_true_do.app_git
      wtd_app_git_role: "server"
      wtd_app_git_server_conf_authorized_key:
        - key: "ssh-rsa foobarbaz foo@bar.baz"
          state: "present"
